const questionsNL = [
    "Noem 3 merken van smartphones",
    "Noem 3 soorten bier",
    "Noem 3 pizza toppings",
    "Noem 3 steden in Nederland",
    "Noem 3 automerken",
    "Noem 3 soorten chocolade",
    "Noem 3 landen in Europa",
    "Noem 3 sporten met een bal",
    "Noem 3 beroemde acteurs",
    "Noem 3 soorten vissen",
    "Noem 3 kleuren op de Nederlandse vlag",
    "Noem 3 supermarkten in Nederland",
    "Noem 3 feestdagen",
    "Noem 3 populaire streamingdiensten",
    "Noem 3 drankjes zonder alcohol",
    "Noem 3 dingen die je in een tas kunt vinden",
    "Noem 3 nummers van een verkeersbord",
    "Noem 3 kledingstukken",
    "Noem 3 snacks die je in de bioscoop eet",
    "Noem 3 landen buiten Europa",
    "Noem 3 soorten kaas",
    "Noem 3 soorten planten",
    "Noem 3 Sinterklaasliedjes",
    "Noem 3 dingen die je bij een bakker koopt",
    "Noem 3 beroepen waar je een uniform draagt",
    "Noem 3 fruitsoorten met een pit",
    "Noem 3 tijdschriften",
    "Noem 3 elektronische apparaten",
    "Noem 3 plekken waar je kunt zwemmen",
    "Noem 3 soorten ijs",
    "Noem 3 bekende Nederlandse sporters",
    "Noem 3 kledingmerken",
    "Noem 3 soorten noten",
    "Noem 3 films van de afgelopen 5 jaar",
    "Noem 3 populaire bordspellen",
    "Noem 3 soorten brood",
    "Noem 3 dingen die geel zijn",
    "Noem 3 fastfoodketens",
    "Noem 3 liedjes van Nederlandse artiesten",
    "Noem 3 hoofdsteden van Aziatische landen",
    "Noem 3 talen die in Europa worden gesproken",
    "Noem 3 Netflix-series",
    "Noem 3 soorten taart",
    "Noem 3 dagen van de week",
    "Noem 3 drankjes met alcohol",
    "Noem 3 vervoermiddelen zonder motor",
    "Noem 3 soorten meubels",
    "Noem 3 dieren in de dierentuin",
    "Noem 3 nummers van Ed Sheeran",
    "Noem 3 onderdelen van een auto",
    "Noem 3 dingen die je in een keuken vindt",
    "Noem 3 beroemde festivals",
    "Noem 3 tv-programmas",
    "Noem 3 dingen die je op je bureau kunt vinden",
    "Noem 3 social media platforms",
    "Noem 3 landen met rood in de vlag",
    "Noem 3 soorten huisdieren",
    "Noem 3 chocoladerepen",
    "Noem 3 muziekinstrumenten",
    "Noem 3 soorten pasta",
    "Noem 3 planeten",
    "Noem 3 sporten zonder bal",
    "Noem 3 dingen die blauw zijn",
    "Noem 3 manieren om te reizen",
    "Noem 3 dingen die je aan de muur hangt",
    "Noem 3 onderdelen van een fiets",
    "Noem 3 boeken van Harry Potter",
    "Noem 3 feestjes in Nederland",
    "Noem 3 landen met een koning of koningin",
    "Noem 3 cocktails",
    "Noem 3 dieren met een staart",
    "Noem 3 bekende schilders",
    "Noem 3 films met superhelden",
    "Noem 3 woorden die rijmen op kat",
    "Noem 3 gerechten met kip",
    "Noem 3 bekende Nederlandse politici",
    "Noem 3 dingen die je in de winter draagt",
    "Noem 3 soorten thee",
    "Noem 3 plekken waar je boeken kunt vinden",
    "Noem 3 kleuren van stoplichten",
    "Noem 3 snacks uit de frituur",
    "Noem 3 dieren met vleugels",
    "Noem 3 Europese rivieren",
    "Noem 3 soorten chips",
    "Noem 3 zangers of zangeressen uit Nederland",
    "Noem 3 dingen die je doet in de zomer",
    "Noem 3 soorten bomen",
    "Noem 3 populaire YouTubers",
    "Noem 3 dieren uit de jungle",
    "Noem 3 manieren om koffie te drinken",
    "Noem 3 soorten groente",
    "Noem 3 landen in Zuid-Amerika",
    "Noem 3 vakantiebestemmingen in Nederland",
    "Noem 3 dingen die je doet op vakantie",
    "Noem 3 soorten water",
    "Noem 3 plekken waar je niet mag bellen",
    "Noem 3 accessoires die je kunt dragen",
    "Noem 3 films van Disney",
    "Noem 3 namen die beginnen met de letter M",
    "Noem 3 dingen die je in een slaapkamer vindt",
    "Noem 3 dieren die in de zee leven",
    "Noem 3 landen in Afrika",
    "Noem 3 dingen die in een badkamer staan",
    "Noem 3 redenen om te lachen",
    "Noem 3 gereedschappen",
    "Noem 3 soorten snoep",
    "Noem 3 dingen die je niet mag vergeten op vakantie",
    "Noem 3 woorden die beginnen met een Z",
    "Noem 3 soorten kaas uit Nederland",
    "Noem 3 bekende schrijvers",
    "Noem 3 soorten dakbedekking",
    "Noem 3 liedjes van Michael Jackson",
    "Noem 3 uitvindingen uit de 20e eeuw",
    "Noem 3 bekende stripfiguren",
    "Noem 3 steden in Duitsland",
    "Noem 3 Nederlandse eilanden",
    "Noem 3 momenten waarop je iemand feliciteert",
    "Noem 3 genres boeken",
    "Noem 3 manieren om te sporten",
    "Noem 3 films met het thema Kerst",
    "Noem 3 soorten drankjes met ijs",
    "Noem 3 landen die met een S beginnen",
    "Noem 3 gerechten die je kunt frituren",
    "Noem 3 instrumenten in een orkest",
    "Noem 3 populaire films van 2024",
    "Noem 3 manieren om afval te scheiden",
    "Noem 3 dieren die in bomen leven",
    "Noem 3 dingen die je in een portemonnee vindt",
    "Noem 3 beroemde stranden",
    "Noem 3 plekken waar je moet fluisteren",
    "Noem 3 onderwerpen waar mensen over ruzie maken",
    "Noem 3 desserts",
    "Noem 3 gebouwen die je in een stad vindt",
    "Noem 3 manieren om water op te warmen",
    "Noem 3 kleuren van een regenboog",
    "Noem 3 dingen die je gebruikt tijdens het koken",
    "Noem 3 soorten koekjes",
    "Noem 3 symbolen op je toetsenbord",
    "Noem 3 historische gebeurtenissen",
    "Noem 3 dieren die in de avond actief zijn",
    "Noem 3 soorten vogels",
    "Noem 3 soorten winterkleding",
    "Noem 3 landen met een koude wintersportplek",
    "Noem 3 landen met tropische eilanden",
    "Noem 3 dingen die je mee naar een picknick neemt",
    "Noem 3 vormen van openbaar vervoer",
    "Noem 3 beroepen in de zorg",
    "Noem 3 muziekinstrumenten zonder snaren",
    "Noem 3 dingen die je in een rugzak stopt",
    "Noem 3 apps die je op je telefoon hebt staan",
    "Noem 3 beroemde internationale sporters",
    "Noem 3 fruitsoorten die geel zijn",
    "Noem 3 populaire frisdranken",
    "Noem 3 landen met veel woestijnen",
    "Noem 3 dieren met strepen",
    "Noem 3 landen met bergen",
    "Noem 3 redenen om te feesten",
    "Noem 3 Netflix-docuseries",
    "Noem 3 gerechten met aardappels",
    "Noem 3 superheldenfilms",
    "Noem 3 soorten rijstgerechten",
    "Noem 3 soorten koffie",
    "Noem 3 dingen die je op een festival tegenkomt",
    "Noem 3 attracties in een pretpark",
    "Noem 3 soorten schoenen",
    "Noem 3 bekende filosofen",
    "Noem 3 talen die in Afrika worden gesproken",
    "Noem 3 instrumenten in een rockband",
    "Noem 3 soorten kledingstukken die je draagt in de zomer",
    "Noem 3 liedjes die iedereen kent",
    "Noem 3 merken van chips",
    "Noem 3 bekende boekenreeksen",
    "Noem 3 dingen die je in een auto vindt",
    "Noem 3 beroemde gebouwen",
    "Noem 3 nationale parken",
    "Noem 3 waterdieren met schubben",
    "Noem 3 beroepen in de techniek",
    "Noem 3 bekende films met robots",
    "Noem 3 gerechten uit Italië",
    "Noem 3 dingen die je aan een sleutelbos hangt",
    "Noem 3 redenen waarom je te laat kunt zijn",
    "Noem 3 soorten huisdieren behalve een hond of kat",
    "Noem 3 bekende dieren uit tekenfilms",
    "Noem 3 redenen om op vakantie te gaan",
    "Noem 3 Nederlandse rivieren",
    "Noem 3 winkels in een winkelcentrum",
    "Noem 3 soorten melkproducten",
    "Noem 3 gerechten die je bakt in een pan",
    "Noem 3 landen met een koninkrijk",
    "Noem 3 bekende internationale bedrijven",
    "Noem 3 dieren die in de lucht leven",
    "Noem 3 manieren om een ei te bereiden",
    "Noem 3 beroemde filmregisseurs",
    "Noem 3 dingen die je doet op een vrije dag",
    "Noem 3 soorten tropische fruit",
    "Noem 3 snacks die je op straat kunt kopen",
    "Noem 3 steden die bekend zijn om hun nachtleven",
    "Noem 3 populaire sportevenementen",
    "Noem 3 groenten die je rauw kunt eten",
    "Noem 3 bekende Nederlandse televisiepresentatoren",
    "Noem 3 beroemde liedjes uit de jaren 80",
    "Noem 3 soorten textiel",
    "Noem 3 Nederlandse merken",
    "Noem 3 dieren die in Afrika leven",
    "Noem 3 historische Nederlandse gebouwen",
    "Noem 3 sporten op de Olympische Winterspelen",
    "Noem 3 dieren die beginnen met de letter K",
    "Noem 3 bekende steden in Frankrijk",
    "Noem 3 soorten alcoholische dranken uit Nederland",
    "Noem 3 dingen die je in een hotelkamer vindt",
    "Noem 3 beroemde bergen of bergketens",
    "Noem 3 beroepen in de media",
    "Noem 3 dingen die je gebruikt om te schrijven",
    "Noem 3 soorten vis die je kunt eten",
    "Noem 3 dingen die je in de tuin vindt",
    "Noem 3 soorten sappen",
    "Noem 3 sporten die met snelheid te maken hebben",
    "Noem 3 bekende buitenlandse YouTubers",
    "Noem 3 landen met een R in hun naam",
    "Noem 3 beroemde architecten",
    "Noem 3 soorten speelgoed",
    "Noem 3 functies van een mobiele telefoon",
    "Noem 3 redenen om vroeg op te staan",
    "Noem 3 gerechten met kaas",
    "Noem 3 dingen die je op een markt kunt kopen",
    "Noem 3 soorten vis die in Nederland gevangen worden",
    "Noem 3 beroemde acteurs uit Hollywood",
    "Noem 3 Nederlandse liedjes",
    "Noem 3 noten of zaden",
    "Noem 3 films met een prijswinnende soundtrack",
    "Noem 3 manieren om naar het werk te gaan",
    "Noem 3 landen in het Midden-Oosten",
    "Noem 3 stampot gerechten",
    "Noem 3 soorten voorgerechten",
    "Noem 3 dingen die je doet op een regenachtige dag",
    "Noem 3 sporten die buiten worden gespeeld",
    "Noem 3 grote evenementen in Nederland",
    "Noem 3 landen die grenzen aan de zee",
    "Noem 3 dingen die je op een verjaardag eet",
    "Noem 3 dieren met een vacht",
    "Noem 3 landen met blauw in hun vlag",
    "Noem 3 dingen die je op een stranddag nodig hebt",
    "Noem 3 redenen om te huilen",
    "Noem 3 onderdelen van een computer",
    "Noem 3 bekende Nederlandse films",
    "Noem 3 populaire internationale muziekgenres",
    "Noem 3 dingen die je doet op een zaterdagavond",
    "Noem 3 gerechten met groenten",
    "Noem 3 accesoires voor in de auto",
    "Noem 5 schoolvakken"
];

const questionsEN = [
    "Name 3 smartphone brands",
    "Name 3 types of beer",
    "Name 3 pizza toppings",
    "Name 3 cities in the Netherlands",
    "Name 3 car brands",
    "Name 3 types of chocolate",
    "Name 3 countries in Europe",
    "Name 3 sports with a ball",
    "Name 3 famous actors",
    "Name 3 types of fish",
    "Name 3 colors on the Dutch flag",
    "Name 3 supermarkets in the Netherlands",
    "Name 3 holidays",
    "Name 3 popular streaming services",
    "Name 3 non-alcoholic drinks",
    "Name 3 things you can find in a bag",
    "Name 3 traffic sign numbers",
    "Name 3 pieces of clothing",
    "Name 3 snacks you eat at the cinema",
    "Name 3 countries outside of Europe",
    "Name 3 types of cheese",
    "Name 3 types of plants",
    "Name 3 Sinterklaas songs",
    "Name 3 things you buy at a bakery",
    "Name 3 professions where you wear a uniform",
    "Name 3 fruits with a pit",
    "Name 3 magazines",
    "Name 3 electronic devices",
    "Name 3 places where you can swim",
    "Name 3 types of ice cream",
    "Name 3 famous Dutch athletes",
    "Name 3 clothing brands",
    "Name 3 types of nuts",
    "Name 3 movies from the last 5 years",
    "Name 3 popular board games",
    "Name 3 types of bread",
    "Name 3 things that are yellow",
    "Name 3 fast food chains",
    "Name 3 songs by Dutch artists",
    "Name 3 capitals of Asian countries",
    "Name 3 languages spoken in Europe",
    "Name 3 Netflix series",
    "Name 3 types of cake",
    "Name 3 days of the week",
    "Name 3 alcoholic drinks",
    "Name 3 vehicles without an engine",
    "Name 3 types of furniture",
    "Name 3 animals in the zoo",
    "Name 3 songs by Ed Sheeran",
    "Name 3 parts of a car",
    "Name 3 things you find in a kitchen",
    "Name 3 famous festivals",
    "Name 3 TV shows",
    "Name 3 things you can find on your desk",
    "Name 3 social media platforms",
    "Name 3 countries with red in their flag",
    "Name 3 types of pets",
    "Name 3 chocolate bars",
    "Name 3 musical instruments",
    "Name 3 types of pasta",
    "Name 3 planets",
    "Name 3 sports without a ball",
    "Name 3 things that are blue",
    "Name 3 ways to travel",
    "Name 3 things you hang on the wall",
    "Name 3 parts of a bicycle",
    "Name 3 Harry Potter books",
    "Name 3 parties in the Netherlands",
    "Name 3 countries with a king or queen",
    "Name 3 cocktails",
    "Name 3 animals with a tail",
    "Name 3 famous painters",
    "Name 3 superhero movies",
    "Name 3 words that rhyme with cat",
    "Name 3 dishes with chicken",
    "Name 3 famous Dutch politicians",
    "Name 3 things you wear in the winter",
    "Name 3 types of tea",
    "Name 3 places where you can find books",
    "Name 3 colors of traffic lights",
    "Name 3 snacks from the fryer",
    "Name 3 animals with wings",
    "Name 3 European rivers",
    "Name 3 types of chips",
    "Name 3 singers from the Netherlands",
    "Name 3 things you do in the summer",
    "Name 3 types of trees",
    "Name 3 popular YouTubers",
    "Name 3 animals from the jungle",
    "Name 3 ways to drink coffee",
    "Name 3 types of vegetables",
    "Name 3 countries in South America",
    "Name 3 vacation destinations in the Netherlands",
    "Name 3 things you do on vacation",
    "Name 3 types of water",
    "Name 3 places where you are not allowed to call",
    "Name 3 accessories you can wear",
    "Name 3 Disney movies",
    "Name 3 names that start with the letter M",
    "Name 3 things you find in a bedroom",
    "Name 3 animals that live in the sea",
    "Name 3 countries in Africa",
    "Name 3 things in a bathroom",
    "Name 3 reasons to laugh",
    "Name 3 tools",
    "Name 3 types of candy",
    "Name 3 things you should not forget on vacation",
    "Name 3 words that start with a Z",
    "Name 3 types of cheese from the Netherlands",
    "Name 3 famous writers",
    "Name 3 types of roofing",
    "Name 3 songs by Michael Jackson",
    "Name 3 inventions from the 20th century",
    "Name 3 famous comic characters",
    "Name 3 cities in Germany",
    "Name 3 Dutch islands",
    "Name 3 occasions when you congratulate someone",
    "Name 3 genres of books",
    "Name 3 ways to exercise",
    "Name 3 Christmas-themed movies",
    "Name 3 types of iced drinks",
    "Name 3 countries that start with an S",
    "Name 3 dishes you can deep fry",
    "Name 3 instruments in an orchestra",
    "Name 3 popular movies of 2024",
    "Name 3 ways to separate waste",
    "Name 3 animals that live in trees",
    "Name 3 things you find in a wallet",
    "Name 3 famous beaches",
    "Name 3 places where you must whisper",
    "Name 3 topics people argue about",
    "Name 3 desserts",
    "Name 3 buildings you find in a city",
    "Name 3 ways to heat up water",
    "Name 3 colors of a rainbow",
    "Name 3 things you use while cooking",
    "Name 3 types of cookies",
    "Name 3 symbols on your keyboard",
    "Name 3 historical events",
    "Name 3 animals that are active in the evening",
    "Name 3 types of birds",
    "Name 3 types of winter clothing",
    "Name 3 countries with cold winter sports places",
    "Name 3 countries with tropical islands",
    "Name 3 things you take to a picnic",
    "Name 3 forms of public transport",
    "Name 3 healthcare professions",
    "Name 3 musical instruments without strings",
    "Name 3 things you put in a backpack",
    "Name 3 apps you have on your phone",
    "Name 3 famous international athletes",
    "Name 3 types of fruit that are yellow",
    "Name 3 popular soft drinks",
    "Name 3 countries with a lot of deserts",
    "Name 3 animals with stripes",
    "Name 3 countries with mountains",
    "Name 3 reasons to celebrate",
    "Name 3 Netflix docuseries",
    "Name 3 dishes with potatoes",
    "Name 3 superhero movies",
    "Name 3 types of rice dishes",
    "Name 3 types of coffee",
    "Name 3 things you find at a festival",
    "Name 3 attractions at an amusement park",
    "Name 3 types of shoes",
    "Name 3 famous philosophers",
    "Name 3 languages spoken in Africa",
    "Name 3 instruments in a rock band",
    "Name 3 types of clothing you wear in the summer",
    "Name 3 songs everyone knows",
    "Name 3 chip brands",
    "Name 3 famous book series",
    "Name 3 things you find in a car",
    "Name 3 famous buildings",
    "Name 3 national parks",
    "Name 3 aquatic animals with scales",
    "Name 3 professions in engineering",
    "Name 3 famous movies with robots",
    "Name 3 dishes from Italy",
    "Name 3 things you hang on a keychain",
    "Name 3 reasons why you might be late",
    "Name 3 types of pets other than a dog or cat",
    "Name 3 famous cartoon animals",
    "Name 3 reasons to go on vacation",
    "Name 3 rivers in the Netherlands",
    "Name 3 stores in a shopping mall",
    "Name 3 types of dairy products",
    "Name 3 dishes you cook in a pan",
    "Name 3 countries with a kingdom",
    "Name 3 famous international companies",
    "Name 3 animals that live in the air",
    "Name 3 ways to prepare an egg",
    "Name 3 famous film directors",
    "Name 3 things you do on a day off",
    "Name 3 types of tropical fruit",
    "Name 3 snacks you can buy on the street",
    "Name 3 cities known for their nightlife",
    "Name 3 popular sporting events",
    "Name 3 vegetables you can eat raw",
    "Name 3 famous Dutch television presenters",
    "Name 3 famous songs from the 80s",
    "Name 3 types of textiles",
    "Name 3 Dutch brands",
    "Name 3 animals that live in Africa",
    "Name 3 historical Dutch buildings",
    "Name 3 sports in the Winter Olympics",
    "Name 3 animals that start with the letter K",
    "Name 3 famous cities in France",
    "Name 3 types of alcoholic drinks from the Netherlands",
    "Name 3 things you find in a hotel room",
    "Name 3 famous mountains or mountain ranges",
    "Name 3 professions in the media",
    "Name 3 things you use to write",
    "Name 3 types of fish you can eat",
    "Name 3 things you find in the garden",
    "Name 3 types of juices",
    "Name 3 sports related to speed",
    "Name 3 famous international YouTubers",
    "Name 3 countries with an R in their name",
    "Name 3 famous architects",
    "Name 3 types of toys",
    "Name 3 functions of a mobile phone",
    "Name 3 reasons to get up early",
    "Name 3 dishes with cheese",
    "Name 3 things you can buy at a market",
    "Name 3 types of fish caught in the Netherlands",
    "Name 3 famous Hollywood actors",
    "Name 3 Dutch songs",
    "Name 3 types of nuts or seeds",
    "Name 3 movies with an award-winning soundtrack",
    "Name 3 ways to get to work",
    "Name 3 countries in the Middle East",
    "Name 3 types of mashed potato dishes",
    "Name 3 types of appetizers",
    "Name 3 things you do on a rainy day",
    "Name 3 sports played outdoors",
    "Name 3 major events in the Netherlands",
    "Name 3 countries bordering the sea",
    "Name 3 things you eat at a birthday party",
    "Name 3 animals with fur",
    "Name 3 countries with blue in their flag",
    "Name 3 things you need on a beach day",
    "Name 3 reasons to cry",
    "Name 3 components of a computer",
    "Name 3 famous Dutch movies",
    "Name 3 popular international music genres",
    "Name 3 things you do on a Saturday night",
    "Name 3 dishes with vegetables",
    "Name 3 accessories for the car",
    "Name 5 school subjects"
];


let currentLanguage = "nl"; // Standaard taal

const interfaceTexts = {
    nl: {
        title: "5 Seconden Spel",
        startingText: "Klik op \"Nieuwe vraag\" om te beginnen!",
        newQuestionButton: "Nieuwe vraag",
        startButton: "Start",
        timeUp: "Tijd is om!",
        timeUpMessage: "De tijd is voorbij!"
    },
    en: {
        title: "5 Second Game",
        startingText: "Click on \"New question\" to begin!",
        newQuestionButton: "New question",
        startButton: "Start",
        timeUp: "Time's up!",
        timeUpMessage: "Time's up!"
    }
};

// DOM-elementen
const languageToggle = document.getElementById("language-toggle");
const gameTitle = document.getElementById("game-title");
const newQuestionButton = document.getElementById("new-question-button");
const startTimerButton = document.getElementById("start-timer-button");
const questionElement = document.getElementById("question");
const timerElement = document.getElementById("timer");
const statusMessage = document.getElementById("status-message");

let usedQuestions = [];
let timer;
let timeLeft = 5;
let currentQuestion = ''; // Huidige vraag opslaan
let currentQuestionIndex = -1; // De index van de huidige vraag

// Functie om interface te updaten op basis van taal
function updateInterfaceLanguage() {
    const texts = interfaceTexts[currentLanguage];
    gameTitle.textContent = texts.title;
    questionElement.textContent = texts.startingText;
    newQuestionButton.textContent = texts.newQuestionButton;
    startTimerButton.textContent = texts.startButton;

    // Vertaal de vraag naar de juiste taal
    if (currentQuestionIndex !== -1) {
        const questions = currentLanguage === "nl" ? questionsNL : questionsEN;
        questionElement.textContent = questions[currentQuestionIndex];
    }
}

// Nieuwe vraag genereren
newQuestionButton.addEventListener("click", () => {
    const questions = currentLanguage === "nl" ? questionsNL : questionsEN;

    // Controleer of alle vragen zijn gebruikt
    if (usedQuestions.length === questions.length) {
        usedQuestions = [];
        alert(currentLanguage === "nl" ?
            "Alle vragen zijn gebruikt! De lijst wordt opnieuw gestart." :
            "All questions have been used! The list will reset.");
    }

    // Kies een nieuwe vraag
    let randomIndex;
    do {
        randomIndex = Math.floor(Math.random() * questions.length);
    } while (usedQuestions.includes(randomIndex));

    usedQuestions.push(randomIndex);
    currentQuestionIndex = randomIndex; // Bewaar de index van de gekozen vraag
    questionElement.textContent = questions[randomIndex];

    // Reset status en timer
    statusMessage.textContent = "";
    timerElement.textContent = timeLeft;
    timerElement.classList.add("hidden");

    // Knoppen aanpassen
    newQuestionButton.classList.add("hidden");
    startTimerButton.classList.remove("hidden");
});

// Timer starten
startTimerButton.addEventListener("click", () => {
    timerElement.classList.remove("hidden");
    startTimerButton.classList.add("hidden");

    timeLeft = 5;
    timerElement.textContent = timeLeft;

    timer = setInterval(() => {
        timeLeft--;
        timerElement.textContent = timeLeft;

        if (timeLeft <= 0) {
            clearInterval(timer);
            timerElement.textContent = interfaceTexts[currentLanguage].timeUp;
            statusMessage.textContent = interfaceTexts[currentLanguage].timeUpMessage;

            // Knoppen aanpassen
            newQuestionButton.classList.remove("hidden");
        }
    }, 1000);
});

// Taal toggle
languageToggle.addEventListener("change", (e) => {
    currentLanguage = e.target.value;
    updateInterfaceLanguage(); // Update de interface met de nieuwe taal
});

// Initialiseer met standaardtaal
updateInterfaceLanguage();